Repository prajapatihet/donorconnect, pull requests merged in 2024-10, with the labels that each got.

#3 Update README.md
  README.md
Labels: documentation

#11 updated the signup page
  lib/Pages/signup.dart
Labels: level1, gssoc-ext, hacktoberfest-accepted

#18 Fixed issue #16: Obscured password in login and sign-up pages
  lib/Utils/Textbox.dart
  lib/views/pages/login/login.dart
  lib/views/pages/register/signup.dart
Labels: level1, gssoc-ext, hacktoberfest-accepted

#22 Screen for User Profile Setup #15
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/cubit/profile_cubit.dart
  lib/cubit/profile_state.dart
  lib/main.dart
  lib/views/pages/login/login.dart
  lib/views/pages/main_home/bottom_nav.dart
  lib/views/pages/main_home/homepage.dart
  lib/views/pages/profile/profile_screen.dart
  lib/views/pages/register/signup.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#21 Addition: Navigate Back Button on Sign Up Page
  lib/views/pages/register/signup.dart
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#23 Created Page for Locate BloodBank
  lib/views/pages/locateBloodbank/locateBloodBank.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted

#25 Update README.md
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#32 authentication completed
  android/app/build.gradle
  android/app/google-services.json
  android/settings.gradle
  firebase.json
  lib/Utils/show_snackbar.dart
  lib/cubit/auth/auth_cubit.dart
  lib/cubit/auth/auth_state.dart
  lib/cubit/profile/profile_cubit.dart
  lib/cubit/profile/profile_state.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/models/user_model.dart
  lib/views/pages/login/login.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  lib/views/pages/profile/profile_screen.dart
  lib/views/pages/register/signup.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#35 fixed all .md links to main readme file
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#37 #36 [BUG] IOS Build failing resolved.
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  lib/main.dart
  lib/secrets.dart
  lib/views/pages/locateBloodbank/locateBloodBank.dart
  lib/views/pages/locate_blood_banks/locate_blood_banks.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner/GoogleService-Info.plist
Labels: bug, level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#38 modifications made
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#39 Integrated Blood Bank API and Display Blood Bank List - Resolves #13
  android/app/google-services.json
  firebase.json
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubit/locate_blood_banks/locate_blood_banks_cubit.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/services/blood_bank_service.dart
  lib/views/pages/locate_blood_banks/locate_blood_banks.dart
  macos/Runner.xcodeproj/project.pbxproj
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#40 In Sign Up Page Added validation for Email,Password,Phone Number
  lib/views/pages/register/signup.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#42 Create workflow yml file
  .github/workflows/greetings.yml
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#45 Added Donor and Recipient Verification System
  lib/Utils/validation_helpers.dart
  lib/main.dart
  lib/models/verification_status.dart
  lib/services/verification_service.dart
  lib/views/verificationform.dart
  pubspec.yaml
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted

#54 name in profile page made dynamic
  lib/cubit/auth/auth_cubit.dart
  lib/cubit/profile/profile_state.dart
  lib/views/pages/login/login.dart
  lib/views/pages/main_home/homepage.dart
  lib/views/pages/register/signup.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#57 Navigation improved and integrated transition effects in application
  lib/views/pages/locate_blood_banks/locate_blood_banks.dart
  lib/views/pages/login/login.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  lib/views/pages/main_home/homepage.dart
  lib/views/pages/profile/profile_screen.dart
  lib/views/pages/register/signup.dart
  lib/views/pages/welcome/welcome_screen.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#63 Fixed #59
  lib/cubit/auth/auth_cubit.dart
  lib/views/pages/login/login.dart
  lib/views/pages/register/signup.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#61 new feature🦄: introduced localization to donnorconnect
  l10n.yaml
  lib/l10n/intl_en.arb
  lib/l10n/intl_gu.arb
  lib/l10n/intl_hi.arb
  lib/language/cubit/language_cubit.dart
  lib/language/helper/langauge_popup.dart
  lib/language/helper/language.dart
  lib/language/helper/language_extention.dart
  lib/language/services/language_repositoty.dart
  lib/main.dart
  lib/views/pages/locate_blood_banks/locate_blood_banks.dart
  lib/views/pages/login/login.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  lib/views/pages/main_home/homepage.dart
  lib/views/pages/profile/profile_screen.dart
  lib/views/pages/register/signup.dart
  lib/views/pages/welcome/welcome_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#64 Added Feature #60
  lib/views/pages/main_home/homepage.dart
  pubspec.lock
  pubspec.yaml
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#68 password field updated
  lib/Utils/Textbox.dart
  lib/views/pages/register/signup.dart
Labels: bug, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#69 Added Camp Page (Fixes #14)
  android/app/src/main/AndroidManifest.xml
  android/settings.gradle
  ios/Runner/Info.plist
  lib/views/pages/camps/campsPage.dart
  lib/views/pages/main_home/homepage.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#70 forgot password functionality integrated
  lib/cubit/forgot_password/forgot_password_cubit.dart
  lib/cubit/forgot_password/forgot_password_state.dart
  lib/views/pages/forgot_password/change-password.dart
  lib/views/pages/forgot_password/forgot-password.dart
  lib/views/pages/login/login.dart
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#72 Implement Auto-Redirect to Homepage Based on User Authentication Status
  lib/views/pages/welcome/welcome_screen.dart
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#73 Feat: Calendar feature added
  assets/images/empty_calendar.png
  lib/views/common_widgets/events_card.dart
  lib/views/pages/camps/calendarPage.dart
  lib/views/pages/camps/campsPage.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#77 changed form styling and and save button styling in profile screen
  lib/views/pages/profile/profile_screen.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#79 Create pr-checker.yaml
  .github/workflows/pr-checker.yaml
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#81 Added build apk action
  .github/workflows/build_apk.yml
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#82 changed the addform styling in campus page
  lib/views/pages/camps/campsPage.dart
Labels: enhancement, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#84 feat: Google oAuth added
  assets/images/google.png
  lib/cubit/auth/auth_cubit.dart
  lib/views/pages/login/login.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#87 added toggle button to toggle b/w light and dark theme
  lib/cubit/theme_toggle/theme_cubit.dart
  lib/cubit/theme_toggle/value_cubit.dart
  lib/main.dart
  lib/views/common_widgets/toggle_button.dart
  lib/views/pages/profile/profile_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#85 added the Search Page features
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  lib/main.dart
  lib/views/pages/main_home/bottom_nav.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  lib/views/pages/main_home/homepage.dart
  lib/views/pages/search/search_screen.dart
  lib/views/pages/search/widgets/blood_bank_form.dart
  lib/views/pages/search/widgets/blood_donor_form.dart
  pubspec.lock
  pubspec.yaml
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#93 change the styling of forget password screen buttons
  lib/views/pages/forgot_password/change-password.dart
  lib/views/pages/forgot_password/forgot-password.dart
  pubspec.lock
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#89 Update Contributors.md
  Contributors.md
Labels: documentation, level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#98 Added Onboarding Featues and pages to app
  assets/images/OnBoarding1.jpg
  assets/images/OnBoarding2.jpg
  assets/images/OnBoarding3.jpg
  lib/Utils/constants/images_string.dart
  lib/Utils/constants/text_string.dart
  lib/main.dart
  lib/views/controllers/onboarding/onboarding_controller.dart
  lib/views/pages/onboarding/onboarding.dart
  lib/views/pages/onboarding/widgets/onboarding_dot_navigation.dart
  lib/views/pages/onboarding/widgets/onboarding_next_button.dart
  lib/views/pages/onboarding/widgets/onboarding_page.dart
  lib/views/pages/onboarding/widgets/onboarding_skip.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#99 Added 'Learn More About Blood and Platelet Donation' Page
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/firebase_options.dart
  lib/views/pages/learn_about_donation/learn_about_donation.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#100 Feat: ChatBot Integrated
  .env.example
  .gitignore
  devtools_options.yaml
  lib/main.dart
  lib/views/pages/main_home/chatbot.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#101 Automated project structure updation using github workflows, python scripts and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#104 added screen for required button on home page
  PROJECT_STRUCTURE.md
  lib/views/common_widgets/donor_card.dart
  lib/views/common_widgets/rounded_conatiner.dart
  lib/views/common_widgets/rounded_image.dart
  lib/views/pages/Required/required_screen.dart
  lib/views/pages/Required/widgets/choice_chip.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#106 Signup page issue resolved
  lib/views/pages/camps/campsPage.dart
  lib/views/pages/register/signup.dart
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#108 added Screen for the donate button at home page
  PROJECT_STRUCTURE.md
  lib/views/common_widgets/donate_card.dart
  lib/views/pages/Required/required_screen.dart
  lib/views/pages/donate/donate_screen.dart
  lib/views/pages/donate/widgets/donate_screen_tabbar.dart
  lib/views/pages/main_home/home_pages/home_screen.dart
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#109 Handling Correctly the Application Theme
  lib/cubit/theme_toggle/theme_cubit.dart
  lib/cubit/theme_toggle/theme_state.dart
  lib/cubit/theme_toggle/value_cubit.dart
  lib/main.dart
  lib/views/common_widgets/toggle_button.dart
  lib/views/pages/profile/profile_screen.dart
Labels: level2, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#116 Added back-to-top button to README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted
